/** Mesh Branding v1.2.1 */
module.exports.mesh_branding=function(parent){
 var fs=require('fs'),path=require('path');
 var obj={parent:parent,meshServer:parent.parent}; obj.debug=obj.meshServer&&obj.meshServer.debug; obj.exports=['onWebUIStartupEnd','goPageEnd'];
 var pluginDir=__dirname,dataDir=path.resolve(__dirname,'..','..'),cfgPath=path.join(__dirname,'brand-config.json');
 function log(m){try{obj.debug('PLUGIN','Mesh Branding',m);}catch(e){}try{console.log('PLUGIN: Mesh Branding: '+m);}catch(e){}}
 function cfg(){try{return JSON.parse(fs.readFileSync(cfgPath,'utf8'));}catch(e){return {};}}
 function norm(h){return String(h||'').trim().toLowerCase().split(':')[0];}
 function host(req){return norm((req&&req.headers&&(req.headers['x-forwarded-host']||req.headers.host))||'');}
 function mime(f){var e=path.extname(f).toLowerCase();if(e==='.png')return'image/png';if(e==='.svg')return'image/svg+xml; charset=utf-8';if(e==='.jpg'||e==='.jpeg')return'image/jpeg';if(e==='.webp')return'image/webp';if(e==='.ico')return'image/x-icon';return'application/octet-stream';}
 function safe(base,rel){rel=String(rel||'').replace(/\\/g,'/').replace(/^\/+/, '');var full=path.resolve(base,rel);return full.indexOf(path.resolve(base))===0?full:null;}
 function brandFor(c,h){var d=c.domains||{};h=norm(h);return d[h]||d[h.replace(/^www\./,'')]||null;}
 function root(name){return String(name||'').toLowerCase()==='data'?dataDir:pluginDir;}
 function pick(req,type){var c=cfg(),h=host(req),b=brandFor(c,h),customRoot=root(type==='favicon'?(c.customFaviconBaseDir||'plugin'):(c.customLogoBaseDir||'plugin')),defRoot=root(type==='favicon'?(c.defaultFaviconBaseDir||'plugin'):(c.defaultLogoBaseDir||'data')),brandFile=b&&(type==='favicon'?b.faviconFile:b.logoFile),defFile=type==='favicon'?c.defaultFaviconFile:c.defaultLogoFile;if(brandFile){var cf=safe(customRoot,brandFile);if(cf&&fs.existsSync(cf)&&fs.statSync(cf).isFile())return {file:cf,host:h,selected:brandFile,root:customRoot,mode:'custom'};}if(defFile){var df=safe(defRoot,defFile);if(df&&fs.existsSync(df)&&fs.statSync(df).isFile())return {file:df,host:h,selected:defFile,root:defRoot,mode:'default'};}return {file:null,host:h,selected:null,root:customRoot+' | '+defRoot,mode:type==='favicon'?'native':'missing'};}
 function send(req,res,p,next){if(!p.file){if(next)return next();res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8','X-Mesh-Branding-Root':p.root||'','X-Mesh-Branding-Mode':p.mode||''});res.end('Mesh Branding: file not found');return;}res.writeHead(200,{'Content-Type':mime(p.file),'Cache-Control':'no-cache, no-store, must-revalidate','X-Mesh-Branding-Host':p.host||'','X-Mesh-Branding-File':p.selected||'','X-Mesh-Branding-Root':p.root||'','X-Mesh-Branding-Mode':p.mode||''});fs.createReadStream(p.file).pipe(res);}
 function getApp(){var a=[obj.meshServer&&obj.meshServer.webserver&&obj.meshServer.webserver.app,obj.meshServer&&obj.meshServer.app,parent&&parent.app,parent&&parent.webserver&&parent.webserver.app];for(var i=0;i<a.length;i++)if(a[i]&&typeof a[i].use==='function')return a[i];return null;}
 function front(app){try{var s=app&&app._router&&app._router.stack;if(Array.isArray(s)&&s.length>1){var l=s.pop();s.unshift(l);return true;}}catch(e){}return false;}
 function title(req){var b=brandFor(cfg(),host(req));return b&&b.documentTitle||null;}
 function css(req){var c=cfg(),b=brandFor(c,host(req))||{},base=c.defaultLogoCss||{},over=b.logoCss||{},x={};Object.keys(base).forEach(k=>x[k]=base[k]);Object.keys(over).forEach(k=>x[k]=over[k]);var m=[],l=[];if(x.mastheadBackgroundSize)m.push('background-size:'+x.mastheadBackgroundSize+' !important');if(x.mastheadBackgroundPosition)m.push('background-position:'+x.mastheadBackgroundPosition+' !important');if(x.mastheadBackgroundRepeat)m.push('background-repeat:'+x.mastheadBackgroundRepeat+' !important');if(x.loginLogoWidth)l.push('width:'+x.loginLogoWidth+' !important');if(x.loginLogoHeight)l.push('height:'+x.loginLogoHeight+' !important');if(x.loginLogoObjectFit)l.push('object-fit:'+x.loginLogoObjectFit+' !important');if(x.loginLogoDisplay)l.push('display:'+x.loginLogoDisplay+' !important');if(x.loginLogoMarginLeft)l.push('margin-left:'+x.loginLogoMarginLeft+' !important');if(x.loginLogoMarginRight)l.push('margin-right:'+x.loginLogoMarginRight+' !important');l.push('max-width:100% !important');var out='';if(m.length)out+='#masthead{'+m.join(';')+';}';if(l.length)out+='img#loginPicture{'+l.join(';')+';}';return out;}
 function should(req){if(!req||String(req.method||'GET').toUpperCase()!=='GET')return false;var p=String(req.url||'/').split('?')[0].toLowerCase();if(p==='/logout'||p.indexOf('/logout')===0)return false;if(!(p==='/'||p==='/login'))return false;if(p.match(/\.(png|jpg|jpeg|gif|webp|ico|css|js|map|svg|woff|woff2|ttf|eot|ashx)$/))return false;var a=String(req.headers&&req.headers.accept||'').toLowerCase();return a.indexOf('text/html')>=0||a.indexOf('*/*')>=0||a==='';}
 function patch(html,t,cs){if(t){var st=String(t).replace(/[&<>]/g,c=>{return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c];});html=/<title>[\s\S]*?<\/title>/i.test(html)?html.replace(/<title>[\s\S]*?<\/title>/i,'<title>'+st+'</title>'):html.replace(/<head[^>]*>/i,m=>m+'<title>'+st+'</title>');}if(cs)html=html.replace(/<head[^>]*>/i,m=>m+'<style id="mesh-branding-size-style">'+cs+'</style>');return html;}
 function htmlMw(req,res,next){if(!should(req))return next();var t=title(req),cs=css(req);if(!t&&!cs)return next();var chunks=[],ow=res.write,oe=res.end,owh=res.writeHead,code=200,headers=null;res.writeHead=function(c,h){code=c||code;headers=h||headers;return res;};res.write=function(ch,enc,cb){if(ch)chunks.push(Buffer.isBuffer(ch)?ch:Buffer.from(ch,enc));if(typeof cb==='function')cb();return true;};res.end=function(ch,enc,cb){if(ch)chunks.push(Buffer.isBuffer(ch)?ch:Buffer.from(ch,enc));var body=Buffer.concat(chunks).toString('utf8');if(code>=300&&code<400){if(owh&&!res.headersSent)try{owh.call(res,code,headers||undefined);}catch(e){}return oe.call(res,body,'utf8',cb);}if(body.indexOf('<html')>=0||body.indexOf('<head')>=0){body=patch(body,t,cs);try{res.setHeader('Content-Length',Buffer.byteLength(body));}catch(e){}try{if(t)res.setHeader('X-Mesh-Branding-Title',t); if(cs)res.setHeader('X-Mesh-Branding-Css','1');}catch(e){}}if(owh&&!res.headersSent)try{owh.call(res,code,headers||undefined);}catch(e){}return oe.call(res,body,'utf8',cb);};next();}
 function logo(req,res){send(req,res,pick(req,'logo'));} function fav(req,res,next){send(req,res,pick(req,'favicon'),next);}
 function route(req,res){var u=(req.url||'/').split('?')[0];if(u==='/'||u==='/logo'||u==='/logo.png')return logo(req,res);if(u==='/favicon'||u==='/favicon.ico'||u==='/favicon.png')return fav(req,res);res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});res.end('Mesh Branding route not found');}
 obj.hook_setupHttpHandlers=function(){var app=getApp();if(!app){log('Express app not found');return;}if(app.__mesh_branding_v121_registered)return;app.__mesh_branding_v121_registered=true;app.use(htmlMw);front(app);var c=cfg(),r=c.route||'/mesh_branding';app.use(r,route);app.use('/loginlogo.png',logo);front(app);app.use('/logo.png',logo);front(app);app.use('/favicon.ico',fav);front(app);app.use('/favicon-303x303.png',fav);var f=front(app);log('registered route '+r+' -> custom:'+pluginDir+', default:'+dataDir);log('intercepted /loginlogo.png, /logo.png and favicon routes'+(f?' (front)':''));log('registered HTML title/style middleware for / and /login only');};
 obj.server_startup=function(){log('loaded, pluginDir='+pluginDir+', dataDir='+dataDir);};
 obj.onWebUIStartupEnd=function(){(function(){'use strict';var CONFIG={"defaultLogoFile": "Aplicado_Logo.png", "defaultFaviconFile": "Aplicado_Favicon.svg", "customLogoBaseDir": "plugin", "defaultLogoBaseDir": "data", "customFaviconBaseDir": "plugin", "defaultFaviconBaseDir": "plugin", "route": "/mesh_branding", "logoEndpoint": "/mesh_branding/logo.png", "faviconEndpoint": "/mesh_branding/favicon.ico", "intercept": {"enabled": true, "paths": ["/loginlogo.png", "/logo.png", "/favicon.ico", "/favicon-303x303.png"]}, "defaultLogoCss": {"mastheadBackgroundSize": "220px auto", "mastheadBackgroundPosition": "12px center", "mastheadBackgroundRepeat": "no-repeat", "loginLogoWidth": "224px", "loginLogoHeight": "60px", "loginLogoObjectFit": "contain", "loginLogoDisplay": "block", "loginLogoMarginLeft": "auto", "loginLogoMarginRight": "auto"}, "options": {"applyDocumentTitle": true, "applyLogoCss": true, "replaceBrandingImagesAfterLogin": false, "replaceMainMeshImage": false, "replaceBackgrounds": false, "preserveInternalTitles": true, "debug": false}, "domains": {"mesh.aplicado.com.br": {"documentTitle": "Acesso Remoto - Aplicado", "logoFile": "Aplicado_Logo.png", "faviconFile": "Aplicado_Favicon.svg"}, "mesh.fastcopy.net.br": {"documentTitle": "Acesso Remoto - FastCopy", "logoFile": "FastCopy_Logo.png", "faviconFile": "FastCopy_Favicon.svg"}, "mesh.crsbrands.com.br": {"documentTitle": "Acesso Remoto - CRS Brands", "logoFile": "CRSBrands_Logo.png", "faviconFile": "CRSBrands_Favicon.svg"}, "mesh.mhs.tec.br": {"documentTitle": "Acesso Remoto - Aplicado", "logoFile": "Aplicado_Logo.png", "faviconFile": "Aplicado_Favicon.svg"}}};function n(h){return String(h||'').trim().toLowerCase().split(':')[0];}function rb(){var h=n(window.location.hostname),d=CONFIG.domains||{},b=d[h]||d[h.replace(/^www\./,'')]||{};return {host:h,brand:b};}function mc(){var base=CONFIG.defaultLogoCss||{},over=(rb().brand||{}).logoCss||{},x={};Object.keys(base).forEach(k=>x[k]=base[k]);Object.keys(over).forEach(k=>x[k]=over[k]);return x;}function apply(){var r=rb();window.__meshBrandingResolved=r;if((CONFIG.options||{}).applyDocumentTitle!==false&&r.brand.documentTitle)document.title=r.brand.documentTitle;var m=document.getElementById('masthead'),x=mc();if(m){if(x.mastheadBackgroundSize)m.style.backgroundSize=x.mastheadBackgroundSize;if(x.mastheadBackgroundPosition)m.style.backgroundPosition=x.mastheadBackgroundPosition;if(x.mastheadBackgroundRepeat)m.style.backgroundRepeat=x.mastheadBackgroundRepeat;}}window.meshBrandingApply=apply;apply();setTimeout(apply,500);setTimeout(apply,1500);})();}; obj.goPageEnd=obj.onWebUIStartupEnd; return obj;
};
