/** Mesh Branding v4.1.0 */
module.exports.mesh_branding=function(parent){
 var fs=require('fs'),path=require('path');
 var obj={parent:parent,meshServer:parent.parent}; obj.debug=obj.meshServer&&obj.meshServer.debug; obj.exports=['onWebUIStartupEnd','goPageEnd'];
 var pluginDir=__dirname,dataDir=path.resolve(__dirname,'..','..'),localConfigPath=path.join(__dirname,'brand-config.json');
 function log(m){try{obj.debug('PLUGIN','Mesh Branding',m);}catch(e){}try{console.log('PLUGIN: Mesh Branding: '+m);}catch(e){}}
 function readConfig(){try{return JSON.parse(fs.readFileSync(localConfigPath,'utf8'));}catch(e){return {};}}
 function normalizeHost(h){return String(h||'').trim().toLowerCase().split(':')[0];}
 function getHost(req){return normalizeHost((req&&req.headers&&(req.headers['x-forwarded-host']||req.headers.host))||'');}
 function getMime(file){var e=path.extname(file).toLowerCase();if(e==='.png')return'image/png';if(e==='.svg')return'image/svg+xml; charset=utf-8';if(e==='.jpg'||e==='.jpeg')return'image/jpeg';if(e==='.webp')return'image/webp';if(e==='.ico')return'image/x-icon';return'application/octet-stream';}
 function safeJoin(base,rel){rel=String(rel||'').replace(/\\/g,'/').replace(/^\/+/, '');var full=path.resolve(base,rel);if(full.indexOf(path.resolve(base))!==0)return null;return full;}
 function brandForHost(cfg,host){var d=cfg.domains||{};host=normalizeHost(host);return d[host]||d[host.replace(/^www\./,'')]||null;}
 function rootFromName(name){name=String(name||'').toLowerCase();return name==='data'?dataDir:pluginDir;}
 function selectLogoFile(req){var cfg=readConfig(),customRoot=rootFromName(cfg.customLogoBaseDir||'plugin'),defaultRoot=rootFromName(cfg.defaultLogoBaseDir||'data'),host=getHost(req),brand=brandForHost(cfg,host);if(brand&&brand.logoFile){var cf=safeJoin(customRoot,brand.logoFile);if(cf&&fs.existsSync(cf)&&fs.statSync(cf).isFile())return {file:cf,host:host,selected:brand.logoFile,root:customRoot,mode:'custom'};}if(cfg.defaultLogoFile){var df=safeJoin(defaultRoot,cfg.defaultLogoFile);if(df&&fs.existsSync(df)&&fs.statSync(df).isFile())return {file:df,host:host,selected:cfg.defaultLogoFile,root:defaultRoot,mode:'default'};}return {file:null,host:host,selected:null,root:customRoot+' | '+defaultRoot,mode:'missing'};}
 function selectFaviconFile(req){var cfg=readConfig(),customRoot=rootFromName(cfg.customFaviconBaseDir||'plugin'),host=getHost(req),brand=brandForHost(cfg,host);if(brand&&brand.faviconFile){var ff=safeJoin(customRoot,brand.faviconFile);if(ff&&fs.existsSync(ff)&&fs.statSync(ff).isFile())return {file:ff,host:host,selected:brand.faviconFile,root:customRoot,mode:'custom'};}return {file:null,host:host,selected:null,root:customRoot,mode:'native'};}
 function titleForReq(req){var cfg=readConfig(),brand=brandForHost(cfg,getHost(req));return brand&&brand.documentTitle||null;}
 function sendFileResult(res,s,notFoundText){if(!s.file){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8','X-Mesh-Branding-Root':s.root||'','X-Mesh-Branding-Mode':s.mode||''});res.end(notFoundText||'Mesh Branding: no file found');return;}res.writeHead(200,{'Content-Type':getMime(s.file),'Cache-Control':'no-cache, no-store, must-revalidate','X-Mesh-Branding-Host':s.host||'','X-Mesh-Branding-File':s.selected||'','X-Mesh-Branding-Root':s.root||'','X-Mesh-Branding-Mode':s.mode||''});fs.createReadStream(s.file).pipe(res);}
 function sendLogo(req,res){sendFileResult(res,selectLogoFile(req),'Mesh Branding: no logo found');}
 function sendFavicon(req,res,next){var s=selectFaviconFile(req);if(!s.file){if(typeof next==='function')return next();return sendFileResult(res,s,'Mesh Branding: no favicon found');}sendFileResult(res,s,'Mesh Branding: no favicon found');}
 function getApp(){var c=[obj.meshServer&&obj.meshServer.webserver&&obj.meshServer.webserver.app,obj.meshServer&&obj.meshServer.app,parent&&parent.app,parent&&parent.webserver&&parent.webserver.app];for(var i=0;i<c.length;i++)if(c[i]&&typeof c[i].use==='function')return c[i];return null;}
 function moveLastLayerToFront(app){try{var st=app&&app._router&&app._router.stack;if(Array.isArray(st)&&st.length>1){var layer=st.pop();st.unshift(layer);return true;}}catch(e){}return false;}
 function shouldPatchHtml(req){if(!req||String(req.method||'GET').toUpperCase()!=='GET')return false;var p=String(req.url||'/').split('?')[0].toLowerCase();if(p==='/logout'||p.indexOf('/logout')===0)return false;if(!(p==='/'||p==='/login'))return false;if(p.match(/\.(png|jpg|jpeg|gif|webp|ico|css|js|map|svg|woff|woff2|ttf|eot|ashx)$/))return false;var a=String(req.headers&&req.headers.accept||'').toLowerCase();return(a.indexOf('text/html')>=0||a.indexOf('*/*')>=0||a==='');}
 function patchTitleHtml(html,title){if(!title)return html;var t=String(title).replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c];});if(/<title>[\s\S]*?<\/title>/i.test(html))return html.replace(/<title>[\s\S]*?<\/title>/i,'<title>'+t+'</title>');if(/<head[^>]*>/i.test(html))return html.replace(/<head[^>]*>/i,function(m){return m+'<title>'+t+'</title>';});return html;}
 function htmlTitleMiddleware(req,res,next){if(!shouldPatchHtml(req))return next();var title=titleForReq(req);if(!title)return next();var chunks=[],oldEnd=res.end,oldWrite=res.write,oldWriteHead=res.writeHead,statusCode=200,headersObj=null;res.writeHead=function(code,headers){statusCode=code||statusCode;headersObj=headers||headersObj;return res;};res.write=function(chunk,encoding,cb){if(chunk)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk,encoding));if(typeof cb==='function')cb();return true;};res.end=function(chunk,encoding,cb){if(chunk)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk,encoding));var body=Buffer.concat(chunks).toString('utf8');if(statusCode>=300&&statusCode<400){if(oldWriteHead&&!res.headersSent){try{oldWriteHead.call(res,statusCode,headersObj||undefined);}catch(e){}}return oldEnd.call(res,body,'utf8',cb);}if(body.indexOf('<html')>=0||body.indexOf('<title')>=0||body.indexOf('<head')>=0){body=patchTitleHtml(body,title);try{res.setHeader('Content-Length',Buffer.byteLength(body));}catch(e){}try{res.setHeader('X-Mesh-Branding-Title',title);}catch(e){}}if(oldWriteHead&&!res.headersSent){try{oldWriteHead.call(res,statusCode,headersObj||undefined);}catch(e){}}return oldEnd.call(res,body,'utf8',cb);};next();}
 function brandingHandler(req,res){var u=req.url||'/',q=u.indexOf('?');if(q>=0)u=u.substring(0,q);if(u==='/'||u==='/logo'||u==='/logo.png')return sendLogo(req,res);if(u==='/favicon'||u==='/favicon.ico'||u==='/favicon.png')return sendFavicon(req,res);res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});res.end('Mesh Branding route not found');}
 function logoHandler(req,res){sendLogo(req,res);}
 function faviconHandler(req,res,next){sendFavicon(req,res,next);}
 obj.hook_setupHttpHandlers=function(){var a=getApp();if(!a){log('Express app not found');return;}if(a.__mesh_branding_v410_registered)return;a.__mesh_branding_v410_registered=true;a.use(htmlTitleMiddleware);moveLastLayerToFront(a);var cfg=readConfig(),route=cfg.route||'/mesh_branding';a.use(route,brandingHandler);a.use('/loginlogo.png',logoHandler);moveLastLayerToFront(a);a.use('/logo.png',logoHandler);moveLastLayerToFront(a);a.use('/favicon.ico',faviconHandler);moveLastLayerToFront(a);a.use('/favicon-303x303.png',faviconHandler);var front=moveLastLayerToFront(a);log('registered route '+route+' -> custom:'+pluginDir+', default:'+dataDir);log('intercepted /loginlogo.png, /logo.png and favicon routes -> custom:'+pluginDir+', default:'+dataDir+(front?' (front)':''));log('registered HTML title middleware for / and /login only');};
 obj.server_startup=function(){log('loaded, pluginDir='+pluginDir+', dataDir='+dataDir);};
 obj.onWebUIStartupEnd=function(){(function(){'use strict';var CONFIG={"defaultLogoFile": "Aplicado_Logo.png", "customLogoBaseDir": "plugin", "defaultLogoBaseDir": "data", "customFaviconBaseDir": "plugin", "route": "/mesh_branding", "logoEndpoint": "/mesh_branding/logo.png", "faviconEndpoint": "/mesh_branding/favicon.ico", "intercept": {"enabled": true, "paths": ["/loginlogo.png", "/logo.png", "/favicon.ico", "/favicon-303x303.png"]}, "options": {"applyDocumentTitle": true, "replaceBrandingImagesAfterLogin": false, "replaceMainMeshImage": false, "replaceBackgrounds": false, "preserveInternalTitles": true, "debug": false}, "domains": {"mesh.aplicado.com.br": {"documentTitle": "Acesso Remoto - Aplicado", "logoFile": "Aplicado_Logo.png", "faviconFile": "Aplicado_Favicon.png"}, "mesh.fastcopy.net.br": {"documentTitle": "Acesso Remoto - FastCopy", "logoFile": "FastCopy_Logo.png", "faviconFile": "FastCopy_Favicon.png"}, "mesh.crsbrands.com.br": {"documentTitle": "Acesso Remoto - CRS Brands", "logoFile": "CRSBrands_Logo.png", "faviconFile": "CRSBrands_Favicon.png"}, "mesh.mhs.tec.br": {"documentTitle": "Acesso Remoto - Aplicado", "logoFile": "Aplicado_Logo.png", "faviconFile": "Aplicado_Favicon.png"}}};function normalizeHost(h){return String(h||'').trim().toLowerCase().split(':')[0];}function resolveBrand(){var h=normalizeHost(window.location.hostname),d=CONFIG.domains||{},b=d[h]||d[h.replace(/^www\./,'')]||{};return {host:h,brand:b};}function apply(){var r=resolveBrand();window.__meshBrandingResolved=r;if((CONFIG.options||{}).applyDocumentTitle!==false&&r.brand.documentTitle)document.title=r.brand.documentTitle;var old=document.getElementById('meshbranding-masthead-logo');if(old&&old.parentNode)old.parentNode.removeChild(old);}window.meshBrandingApply=apply;apply();})();};
 obj.goPageEnd=obj.onWebUIStartupEnd;
 return obj;
};
